{% set name = "swipl" %}
{% set version = "8.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://github.com/SWI-Prolog/swipl-devel/archive/V7.7.0.tar.gz
  # Makes use of git_url as it needs submodules from git, not available in archive 
  # https://github.com/SWI-Prolog/swipl/archive/V8.1.1.tar.gz
  # https://www.swi-prolog.org/download/stable/src/swipl-8.2.1.tar.gz
    url: https://www.swi-prolog.org/download/stable/src/{{ name }}-{{ version }}.tar.gz
    sha256: 331bc5093d72af0c9f18fc9ed83b88ef9ddec0c8d379e6c49fa43739c8bda2fb 
  #git_url: https://github.com/SWI-Prolog/swipl-devel.git
  #git_rev: V{{ version }}

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}      
    - autoconf
    - make
    - cmake
    - ninja
    - libjpeg-turbo
    - ncurses
    - libopenssl-static
    - zlib
    - pkgconfig
    - libuuid
    - libarchive
    - yaml 
  host:
    - curl
    - openjdk
    - gmp
    - ncurses
    - zlib
  run:
    - gmp
    - ncurses
    - zlib

test:
  commands:
    - swipl -h

about:
  home: https://github.com/SWI-Prolog/swipl-devel
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A comprehensive Prolog implementation

extra:
  recipe-maintainers:
    - osallou
