{% set name = "swi-prolog" %}
{% set version = "9.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.swi-prolog.org/download/stable/src/swipl-{{ version }}.tar.gz
  sha256: 896fd51196fd3becd574486da75a924f272e8d63332459292b305986cf101fc3

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - ninja
    - cmake
  host:
    - curl
    - freetype
    - gmp
    - libarchive
    - libedit
    - libjpeg-turbo
    - libunwind
    - libuuid
    - ncurses
    - openjdk
    - openssl
    - readline
    - unixodbc
    - xorg-libice
    - xorg-libx11
    - xorg-libxaw
    - xorg-libxext
    - xorg-libxft
    - xorg-libxinerama
    - xorg-libxmu
    - xorg-libxpm
    - xorg-libxrender
    - xorg-libxt
    - yaml
    - zlib
  run:
    - gmp
    - ncurses
    - zlib

test:
  commands:
    - swipl -g "writeln('hello world')." -t 'halt.'

about:
  home: https://www.swi-prolog.org
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A comprehensive Prolog implementation
  dev_url: https://github.com/SWI-Prolog/swipl-devel
  doc_url: https://www.swi-prolog.org/pldoc/doc_for?object=root

extra:
  recipe-maintainers:
    - Guthur
    - osallou
    - bollwyvl
