# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "9.2.9"
  openjdk_min: "8"

package:
  name: swi-prolog
  version: ${{ version }}

source:
  url: https://www.swi-prolog.org/download/stable/src/swipl-${{ version }}.tar.gz
  sha256: 53f428e2d9bbdf30e53b06c9c42def9a13ff82fc36a111d410fc8b0bc889ee2d

build:
  number: 2
  script:
    file: build-swi-prolog

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then:
        - ninja
        - pkg-config
  host:
    - libarchive
    - libjpeg-turbo
    - openjdk ${{ openjdk_min }}.*
    - openssl
    - pcre2
    - yaml
    - zlib
    # python
    - pip
    - python
    - setuptools >=42
    - setuptools-scm
    # os/arch
    - if: linux
      then:
        - gmp
        - gperftools
        - libxcrypt
        - ossuuid
        - xorg-libxft
    - if: unix
      then:
        - fontconfig
        - libedit
        - ncurses
        - readline
        - unixodbc
        - xorg-libice
        - xorg-libsm
        - xorg-libx11
        - xorg-libxaw
        - xorg-libxext
        - xorg-libxinerama
        - xorg-libxmu
        - xorg-libxpm
        - xorg-libxrender
        - xorg-libxt
    - if: win
      then:
        - pthreads-win32
    - if: not osx
      then:
        - libdb
  run:
    - gmp
    - ncurses
    - openjdk >=${{ openjdk_min }}
    - python
    - zlib
    - if: win
      then:
        - pthreads-win32
    - if: linux
      then:
        - gperftools

tests:
  - script:
      - swipl -g "writeln('hello world')." -t 'halt.'
      - swipl -g test_installation,halt -t halt
  - python:
      imports:
        - janus_swi
        - swiplserver
      pip_check: true
  - requirements:
      run:
        - pytest-cov
    files:
      source:
        - packages/mqi/python/test_prologserver.py
      recipe:
        - test_janus.py
    script:
      - coverage run --source janus_swi --source swiplserver -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=92

about:
  license: BSD-2-Clause AND MIT AND Unicode-DFS-2015
  license_file:
    - LICENSE
    - packages/jpl/LICENSE
    - packages/mqi/python/LICENSE
    - packages/mqi/python/swiplserver/LICENSE
    - packages/sweep/LICENSE
    - packages/utf8proc/LICENSE
    - src/Tests/COPYING

  summary: A comprehensive Prolog implementation
  homepage: https://www.swi-prolog.org
  repository: https://github.com/SWI-Prolog/swipl-devel
  documentation: https://www.swi-prolog.org/pldoc/doc_for?object=root

extra:
  recipe-maintainers:
    - Guthur
    - osallou
    - bollwyvl
