# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "9.2.9"
  python_check_max: "3.14"
  openjdk_min: "8"

package:
  name: swi-prolog
  version: ${{ version }}

source:
  url: https://www.swi-prolog.org/download/stable/src/swipl-${{ version }}.tar.gz
  sha256: 53f428e2d9bbdf30e53b06c9c42def9a13ff82fc36a111d410fc8b0bc889ee2d

build:
  number: 2
  skip: (not linux) or not (is_abi3 and is_python_min)
  script:
    file: build-swi-prolog
  python:
    version_independent: true

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - autoconf
    - cmake
    - ninja
    - pkg-config
  host:
    - curl
    - freetype
    - gmp
    - libarchive
    - libedit
    - libjpeg-turbo
    - libunwind
    - libuuid
    - libxcrypt
    - ncurses
    - openjdk ${{ openjdk_min }}.*
    - openssl
    - readline
    - setuptools
    - unixodbc
    - xorg-libice
    - xorg-libx11
    - xorg-libxaw
    - xorg-libxext
    - xorg-libxft
    - xorg-libxinerama
    - xorg-libxmu
    - xorg-libxpm
    - xorg-libxrender
    - xorg-libxt
    - yaml
    - zlib
    # python stuff
    - pip
    - python
    - python-abi3
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
  run:
    - gmp
    - ncurses
    - zlib
  run_constraints:
    - python >=${{ python_min }}
    - openjdk >=${{ openjdk_min }}
  ignore_run_exports:
    from_package:
      - cross-python_${{ target_platform }}

tests:
  - python:
      imports:
        - janus_swi
        - swiplserver
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - script:
    - swipl -g "writeln('hello world')." -t 'halt.'
  - requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
    files:
      source:
        - packages/mqi/python/test_prologserver.py
      recipe:
        - test_janus.py
    script:
      - coverage run --source janus_swi --source swiplserver -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=92
  - requirements:
      run:
        - pytest-cov
        - python ${{ python_check_max }}.*
    files:
      source:
        - packages/mqi/python/test_prologserver.py
      recipe:
        - test_janus.py
    script:
      - coverage run --source janus_swi --source swiplserver -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=92

about:
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - packages/jpl/LICENSE
    - packages/mqi/python/LICENSE
    - packages/mqi/python/swiplserver/LICENSE
    - packages/sweep/LICENSE
    - packages/utf8proc/LICENSE

  summary: A comprehensive Prolog implementation
  homepage: https://www.swi-prolog.org
  repository: https://github.com/SWI-Prolog/swipl-devel
  documentation: https://www.swi-prolog.org/pldoc/doc_for?object=root

extra:
  recipe-maintainers:
    - Guthur
    - osallou
    - bollwyvl
