travis:
  secure:
    BINSTAR_TOKEN: kiZXpjTDZeSC5WOQg4e/Y/Ikp7XxHZXaP+bo826v7JzSuEhWtu1TNaeNtoEBleGNPdkiAmFhY0HRy94HAEyw35pw1nI9dcrOp9kaxyXtHXWH20rJZlrFV3ytCDI0MEku5+dnZouPJ6P7hvd3+mOc/ElWxS2Gzn1JjFcGOQBCv1pPZAbLj5v123jas0GxUXrUGJ9OpUnR2KshoIRC2l+hF6vojIKLBmm+56x+dGH+oKHbz6CpqbJ4RX1O9C1/9TFtK3g4GlXPwLQG0fzaSTWVIcMM6oFMFuFDWSrPLyXqGX7iyy4FoFbbXFJ4pX7sh1yEXmKOH/P6ZzN3DSrM80y9c8ed3Kf/JnLI/HKrmyhrD1RRf7U5jXUyuSpQolYYjkvv4SZrG0nxAElD3SOdoFBWT1xGuqOuMq+h7CTMEjX2lc5gzp6Q8JdxFCq8UtZcBtidFWul8ppxgHEee6DCtbm2xoe33rlRsA/pINsY6kdxwxWBwdFETDkpEJASmhGkw2GJeaTjRwyYGHAvTOZilNRP4vwtgWumcdU7TzgMBY75MceS0BrGQQyZOaQtItt8ohK6tn78q/7vFoih6BaMdjGOFtUwBE3MQTKsZUbxTOhc/SbqIH39ChDhoMngXhvYWE8tx6e0VVjBhrTakuTZCajM4D7CgOkicSYTtCPASxIG7Zc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
